### PR TITLE
Custom branding for companies

### PR DESCRIPTION
**Pull request by Naghmehd**

### CODE REVIEW

**Comment by vpatel90** [comment]
Alright - DO NOT Merge this yet! I feel like I cheated pretty hard to get these tests to pass. For whatever reason this branch did not have the migration file needed to create companies. Nagmeh tried several times to git pull origin master, but it would not pull down this file. (gets everything else I think) So, I added the file directly on GitHub.

Not sure if this is ok to do, or if there is a bigger problem - I say we wait for Justin's input

**Comment by jah2488** [comment]
Why is there a db.structure file...?

**Comment by vpatel90** [comment]
👍  Should be good to merge

**Comment by reckocp** [comment]
👍

**Pull request merged**
